name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  c:
    name: C
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and test
      run: cd c && make test

  go:
    name: Go
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build and test
      run: cd go && make test

  odin:
    name: Odin
    runs-on: ubuntu-latest

    steps:
    - name: Set up Odin
      run: |
        git clone https://github.com/odin-lang/Odin.git --depth 1 --single-branch --branch=master
        cd Odin
        make
        echo "$(pwd)" >> "$GITHUB_PATH"
        ./odin report

    - name: Build and test
      run: cd go && make test
